/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParseOptions {
  mode?: string
  autoThreshold?: number
  resolveReferences?: boolean
  includeRaw?: boolean
  maxMemory?: number
  timeoutMs?: number
  allowBlocking?: boolean
  chunkSize?: number
  fidelityLevel?: string
  preserveComments?: boolean
  preserveProcessingInstructions?: boolean
  preserveExtensions?: boolean
  preserveAttributeOrder?: boolean
  preserveNamespacePrefixes?: boolean
  canonicalization?: string
  collectStatistics?: boolean
  enableStreaming?: boolean
  streamingThreshold?: number
  validationLevel?: string
  extensionValidation?: boolean
  enableChecksums?: boolean
  memoryLimit?: number
  enableDetailedErrors?: boolean
}
export interface StreamOptions {
  chunkSize?: number
  maxMemory?: number
}
export interface ParsedMessage {
  messageId: string
  messageType: string
  messageDate: string
  senderName: string
  senderId: string
  recipientName: string
  recipientId: string
  version: string
  profile?: string
  releaseCount: number
  trackCount: number
  dealCount: number
  resourceCount: number
  totalDurationSeconds: number
  statistics?: ParseStatistics
  fidelityInfo?: FidelityInfo
}
export interface ParseStatistics {
  parseTimeMs: number
  memoryUsedBytes: number
  elementCount: number
  attributeCount: number
  commentCount: number
  extensionCount: number
  namespaceCount: number
  fileSizeBytes: number
}
export interface FidelityInfo {
  fidelityLevel: string
  canonicalizationAlgorithm: string
  commentsPreserved: boolean
  extensionsPreserved: boolean
  processingInstructionsPreserved: boolean
  attributeOrderPreserved: boolean
  namespacePrefixesPreserved: boolean
}
export interface SanityCheckResult {
  isValid: boolean
  version: string
  errors: Array<string>
  warnings: Array<string>
}
export interface StreamedRelease {
  releaseReference: string
  title: string
  releaseType?: string
  resourceCount: number
}
export interface ProgressInfo {
  bytesProcessed: number
  releasesParsed: number
  elapsedMs: number
}
export declare class DdexParser {
  constructor()
  detectVersion(xml: string): string
  parseSync(xml: string, options?: ParseOptions | undefined | null): ParsedMessage
  parse(xml: string, options?: ParseOptions | undefined | null): Promise<ParsedMessage>
  sanityCheck(xml: string): Promise<SanityCheckResult>
  stream(xml: string, options?: StreamOptions | undefined | null): ReleaseStream
}
export declare class ReleaseStream {
  next(): Promise<StreamedRelease | null>
  progress(): Promise<ProgressInfo>
}
